---
title: "Milestone 8"
author: "Chelsea Marlborough"
date: "11/17/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
library(genius)
library(stringr)
library(wordcloud)
library(RColorBrewer)
library(tm)
library(NLP)
library(SnowballC)


```


```{r songs}

# Here is where I begin to read in the lyrics of the songs. I named each lyric
# set by the song name.

gods_plan <- genius_lyrics("drake", "god's plan")

sad <- genius_lyrics("xxxtentacion", "sad!")

rockstar <- genius_lyrics("post malone", "rockstar")

psycho <- genius_lyrics("post malone", "psycho")

in_my_feelings <- genius_lyrics("drake", "in my feelings")

better_now <- genius_lyrics("post malone", "better now")

i_like_it <- genius_lyrics("cardi b", "i like it")

lucid_dreams <- genius_lyrics("juice wrld", "lucid dreams")

nice_for_what <- genius_lyrics("drake", "nice for what")

all_the_stars <- genius_lyrics("kendrick lamar", "all the stars")

moonlight <- genius_lyrics("xxxtentacion", "moonlight")

look_alive <- genius_lyrics("blocboy jb", "look alive")

te_bote <- genius_lyrics("nio garcia, casper magico & bad bunny", "te bote (remix)")

jocelyn_flores <- genius_lyrics("xxxtentacion", "jocelyn flores")

taste <- genius_lyrics("tyga", "taste")

i_fall_apart <- genius_lyrics("post malone", "i fall apart")

changes <- genius_lyrics("xxxtentacion", "changes")

river <- genius_lyrics("eminem", "river")

sicko_mode <- genius_lyrics("travis scott", "sicko mode")

ric_flair_drip <- genius_lyrics("offset & metro boomin", "ric flair drip")

freaky_friday <- genius_lyrics("lil dicky", "freaky friday")

fefe <- genius_lyrics("6ix9ine", "fefe")

xo_tour_Llif3 <- genius_lyrics("lil uzi vert", "xo tour llif3")

nonstop <- genius_lyrics("drake", "nonstop")

fuck_love <- genius_lyrics("xxxtentacion", "fuck love")

walk_it_talk_it <- genius_lyrics("migos", "walk it talk it")

him_n_i <- genius_lyrics("g-eazy", "him & i")

candy_paint <- genius_lyrics("post malone", "candy paint")

congratulations <- genius_lyrics("post malone", "congratulations")

plug_walk <- genius_lyrics("rich the kid", "plug walk")

stir_fry <- genius_lyrics("migos", "stir fry")

humble <- genius_lyrics("kendrick lamar", "humble.")

vaina_loca <- genius_lyrics("ozuna", "vaina loca")

siguelo_bailando <- genius_lyrics("ozuna", "siguelo bailando")

yes_indeed <- genius_lyrics("lil baby & drake", "yes indeed")

everybody_dies_in_their_nightmares <- genius_lyrics("xxxtentacion", "everybody dies in their nightmares")

one_kiss <- genius_lyrics("calvin harris", "one kiss")

idgaf <- genius_lyrics("dua lipa", "idgaf")

friends <- genius_lyrics("marshmello", "friends")

havana <- genius_lyrics("camila cabello", "havana")

girls_like_you <- genius_lyrics("maroon 5", "girls like you")

the_middle <- genius_lyrics("zedd", "the middle")

no_tears_left_to_cry <- genius_lyrics("ariana grande", "no tears left to cry")

x <- genius_lyrics("nicky jam", "x")

these_days <- genius_lyrics("rudimental", "these days")

mine <- genius_lyrics("bazzi", "mine")

youngblood <- genius_lyrics("5 seconds of summer", "youngblood")

new_rules <- genius_lyrics("dua lipa", "new rules")

shape_of_you <- genius_lyrics("ed sheeran", "shape of you")

love_lies <- genius_lyrics("khalid", "love lies")

meant_to_be <- genius_lyrics("bebe rexha", "meant to be")

perfect <- genius_lyrics("ed sheeran", "perfect")

solo <- genius_lyrics("clean bandit", "solo")

nevermind <- genius_lyrics("dennis lloyd", "nevermind")

echame_la_culpa <- genius_lyrics("luis fonsi & demi lovato", "echame la culpa")

eastside <- genius_lyrics("benny blanco", "eastside")

never_be_the_same <- genius_lyrics("camila cabello", "never be the same")

wolves <- genius_lyrics("selena gomez", "wolves")

in_my_mind <- genius_lyrics("dynoro & gigi d'agostino", "in my mind")

dura <- genius_lyrics("daddy yankee", "dura")

thunder <- genius_lyrics("imagine dragons", "thunder")

me_niego <- genius_lyrics("reik", "me niego")

jackie_chan <- genius_lyrics("tiesto", "jackie chan")

finesse <- genius_lyrics("bruno mars", "finesse")

back_to_you <- genius_lyrics("selena gomez", "back to you")

let_you_down <- genius_lyrics("nf", "let you down")

call_out_my_name <- genius_lyrics("the weeknd", "call out my name")

happier <- genius_lyrics("marshmello", "happier")

too_good_at_goodbyes <- genius_lyrics("sam smith", "too good at goodbyes")

believer <- genius_lyrics("imagine dragons", "believer")

rise <- genius_lyrics("jonas blue", "rise")

body <- genius_lyrics("loud luxury", "body")

sin_pijama <- genius_lyrics("becky g", "sin pijama")

two_thousand_two <- genius_lyrics("anne-marie", "2002")

in_my_blood <- genius_lyrics("shawn mendes", "in my blood")

silence <- genius_lyrics("marshmello", "silence")

god_is_a_woman <- genius_lyrics("ariana grande", "god is a woman")

dejala_que_vuelva <- genius_lyrics("piso 21", "dejala que vuelva")

flames <- genius_lyrics("david guetta", "flames")

what_lovers_do <- genius_lyrics("maroon 5", "what lovers do")

taki_taki <- genius_lyrics("dj snake", "taki taki")

let_me_go <- genius_lyrics("hailee steinfeld", "let me go")

feel_it_still <- genius_lyrics("portugal the man", "feel it still")

pray_for_me <- genius_lyrics("the weeknd & kendrick lamar", "pray for me")

one_two_three <- genius_lyrics("sofia reyes", "1, 2, 3")

criminal <- genius_lyrics("natti natasha", "criminal")

lovely <- genius_lyrics("billie eilish", "lovely")

perfect_duet <- genius_lyrics("ed sheeran", "perfect duet")

corazon <- genius_lyrics("maluma", "corazon")

young_dumb_n_broke <- genius_lyrics("khalid", "young dumb & broke")

downtown <- genius_lyrics("anitta", "downtown")

bella <- genius_lyrics("wolfine", "bella")

promises <- genius_lyrics("calvin harris", "promises")

i_like_me_better <- genius_lyrics("lauv", "i like me better")

this_is_me <- genius_lyrics("keala settle", "this is me")

rewrite_the_stars <- genius_lyrics("zac efron", "rewrite the stars")

i_miss_you <- genius_lyrics("clean bandit", "i miss you")

no_brainer <- genius_lyrics("dj khaled", "no brainer")

dusk_till_dawn <- genius_lyrics("zayn", "dusk till dawn")

be_alright <- genius_lyrics("dean lewis", "be alright")

```


```{r combine into one dataframe}

# Working on somehow making on large data set. I haven't figured out to do this
# perfectly yet or separate the individual words. A work in progress.

lyrics <- bind_rows(gods_plan, sad, rockstar, psycho, in_my_feelings, better_now, i_like_it, lucid_dreams, nice_for_what, all_the_stars, moonlight, look_alive, te_bote, jocelyn_flores, taste, i_fall_apart, changes, river, sicko_mode, ric_flair_drip, freaky_friday, fefe, xo_tour_Llif3, nonstop, fuck_love, walk_it_talk_it, him_n_i, candy_paint, congratulations, plug_walk, stir_fry, humble, vaina_loca, siguelo_bailando, yes_indeed, everybody_dies_in_their_nightmares, one_kiss, idgaf, friends, havana, girls_like_you, the_middle, no_tears_left_to_cry, x, these_days, mine, youngblood, new_rules, shape_of_you, love_lies, meant_to_be, perfect, solo, nevermind, echame_la_culpa, eastside, never_be_the_same, wolves, in_my_mind, dura, thunder, me_niego, jackie_chan, finesse, back_to_you, let_you_down, call_out_my_name, happier, too_good_at_goodbyes, believer, rise, body, sin_pijama, two_thousand_two, in_my_blood, silence, god_is_a_woman, dejala_que_vuelva, flames, what_lovers_do, taki_taki, let_me_go, feel_it_still, pray_for_me, one_two_three, criminal, lovely, perfect_duet, corazon, young_dumb_n_broke, downtown, bella, promises, i_like_me_better, this_is_me, rewrite_the_stars, i_miss_you, no_brainer, dusk_till_dawn, be_alright) %>% 
  separate_rows(lyric, sep = " ") %>% 
  separate_rows(lyric, sep = "[!-&(-.]") %>% 
  select(lyric)

cloud <- Corpus(VectorSource(lyrics))
cloud2 <- tm_map(cloud, removePunctuation)
cloud2 <- tm_map(cloud2, removeWords, stopwords("english"))

a <- TermDocumentMatrix(cloud2)
b <- as.matrix(a)
c <- sort(rowSums(b), decreasing = TRUE)
d <- data.frame(word = names(c), freq = c)


set.seed(1234)
wordcloud(words = d$word, freq = d$freq, min.freq = 1, max.words = 100, random.order = FALSE, rot.per = 0.35, colors = brewer.pal(8, "Greens"))


```





